name: CrowdAcademy
favicon: null
layout_spectrum: 0.914959997870028
typography_spectrum: 0.8522220652084798
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#59c440'
    - '#363d44'
    - '#ec0000'
    - '#f26550'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
